# options from Mnemosy for libKtx

set(KTX_FEATURE_DOC             OFF CACHE BOOL "" FORCE)
set(KTX_FEATURE_GL_UPLOAD        ON CACHE BOOL "" FORCE)
set(KTX_FEATURE_JNI             OFF CACHE BOOL "" FORCE)
set(KTX_FEATURE_KTX1             ON CACHE BOOL "" FORCE)
set(KTX_FEATURE_KTX2             ON CACHE BOOL "" FORCE)
set(KTX_FEATURE_PY              OFF CACHE BOOL "" FORCE)
set(KTX_FEATURE_STATIC_LIBRARY   ON CACHE BOOL "" FORCE)
set(KTX_FEATURE_TESTS           OFF CACHE BOOL "" FORCE)
set(KTX_FEATURE_TOOLS           OFF CACHE BOOL "" FORCE)
set(KTX_FEATURE_TOOLS_CTS       OFF CACHE BOOL "" FORCE)
set(KTX_FEATURE_VK_UPLOAD       OFF CACHE BOOL "" FORCE)
set(KTX_WERROR                  ON CACHE BOOL "" FORCE)
