# options from Mnemosy for libKtx

set(KTX_FEATURE_DOC             OFF CACHE BOOL "" FORCE)
set(KTX_FEATURE_JNI             OFF CACHE BOOL "" FORCE)
set(KTX_FEATURE_PY              OFF CACHE BOOL "" FORCE)
set(KTX_FEATURE_STATIC_LIBRARY  ON CACHE BOOL "" FORCE)
set(KTX_FEATURE_TESTS           OFF CACHE BOOL "" FORCE)
set(KTX_FEATURE_TOOLS           OFF CACHE BOOL "" FORCE)
set(KTX_FEATURE_TOOLS_CTS       OFF CACHE BOOL "" FORCE)
set(KTX_FEATURE_VK_UPLOAD       OFF CACHE BOOL "" FORCE)
set(KTX_WERROR                  OFF CACHE BOOL "" FORCE)
