

set(ASSIMP_ANDROID_JNIIOSYYSTEM   			OFF CACHE BOOL "" FORCE)
set(ASSIMP_ASAN            					OFF CACHE BOOL "" FORCE)

set(ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT	OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT	ON CACHE BOOL "" FORCE)

set(ASSIMP_BUILD_ASSIMP_TOOLS			OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_DRACO					OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_FRAMEWORK				OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_NONFREE_C4D_IMPORTER	OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_SAMPLES				OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_TESTS					OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_USD_IMPORTER			OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_USD_VERBOSE_LOGS		OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_USE_CCACHE				OFF CACHE BOOL "" FORCE)

set(ASSIMP_BUILD_ZLIB         OFF CACHE BOOL "" FORCE)

set(ASSIMP_COVERALLS				OFF CACHE BOOL "" FORCE)
set(ASSIMP_DOUBLE_PRECISION			OFF CACHE BOOL "" FORCE)
set(ASSIMP_HEADERCHECK				OFF CACHE BOOL "" FORCE)
set(ASSIMP_HUNTER_ENABLED			OFF CACHE BOOL "" FORCE)
set(ASSIMP_IGNORE_GIT_HASH			OFF CACHE BOOL "" FORCE)
set(ASSIMP_INJECT_DEBUG_POSTFIX		OFF CACHE BOOL "" FORCE)
set(ASSIMP_INSTALL                	OFF CACHE BOOL "" FORCE)
set(ASSIMP_INSTALL_PDB            	OFF CACHE BOOL "" FORCE)

set(ASSIMP_NO_EXPORT                		ON CACHE BOOL "" FORCE)

set(ASSIMP_OPT_BUILD_PACKAGES				OFF CACHE BOOL "" FORCE)
set(ASSIMP_RAPIDJSON_NO_MEMBER_ITERATOR     OFF CACHE BOOL "" FORCE)
set(ASSIMP_UBSAN                			OFF CACHE BOOL "" FORCE)
set(ASSIMP_WARNINGS_AS_ERRORS                ON CACHE BOOL "" FORCE)
