# options from Mnemosy for Assimp

set(BUILD_SHARED_LIBS             OFF CACHE BOOL "" FORCE)
set(ASSIMP_BUILD_TESTS            OFF CACHE BOOL "" FORCE)
set(ASSIMP_INJECT_DEBUG_POSTFIX   OFF CACHE BOOL "" FORCE)
set(ASSIMP_INSTALL                OFF CACHE BOOL "" FORCE)
