# options from Mnemosy for SpdLog


set(SPDLOG_BUILD_ALL  OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_BENCH  OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_EXAMPLE  OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_EXAMPLE_HO  OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_PIC  OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_SHARED  OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_TESTS  OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_TESTS_HO  OFF CACHE BOOL "" FORCE)
set(SPDLOG_BUILD_WARNINGS  OFF CACHE BOOL "" FORCE)


set(SPDLOG_CLOCK_COARSE  OFF CACHE BOOL "" FORCE)
set(SPDLOG_DISABLE_DEFAULT_LOGGER  OFF CACHE BOOL "" FORCE)
set(SPDLOG_ENABLE_PCH  OFF CACHE BOOL "" FORCE)
set(SPDLOG_FMT_EXTERNAL  OFF CACHE BOOL "" FORCE)
set(SPDLOG_FMT_EXTERNAL_HO  OFF CACHE BOOL "" FORCE)
set(SPDLOG_INSTALL  OFF CACHE BOOL "" FORCE)
set(SPDLOG_NO_ATOMIC_LEVELS  OFF CACHE BOOL "" FORCE)
set(SPDLOG_NO_EXCEPTIONS  OFF CACHE BOOL "" FORCE)
set(SPDLOG_NO_THREAD_ID  OFF CACHE BOOL "" FORCE)
set(SPDLOG_NO_TLS  OFF CACHE BOOL "" FORCE)
set(SPDLOG_PREVENT_CHILD_FD  OFF CACHE BOOL "" FORCE)
set(SPDLOG_SANITIZE_ADDRESS  OFF CACHE BOOL "" FORCE)

set(SPDLOG_SYSTEM_INCLUDES  ON CACHE BOOL "" FORCE)
set(SPDLOG_TIDY             OFF CACHE BOOL "" FORCE)
set(SPDLOG_USE_STD_FORMAT   ON CACHE BOOL "" FORCE)

set(SPDLOG_WCHAR_FILENAMES  OFF CACHE BOOL "" FORCE)
set(SPDLOG_WCHAR_SUPPORT   	OFF CACHE BOOL "" FORCE)


