
set(OPENEXR_BUILD_EXAMPLES 	OFF CACHE BOOL "" FORCE)
set(OPENEXR_BUILD_LIBS 		ON CACHE BOOL "" FORCE)
set(OPENEXR_BUILD_PYTHON 	OFF CACHE BOOL "" FORCE)
set(OPENEXR_BUILD_TOOLS 	OFF CACHE BOOL "" FORCE)

set(OPENEXR_ENABLE_LARGE_STACK 		OFF CACHE BOOL "" FORCE)
set(OPENEXR_ENABLE_THREADING 		ON CACHE BOOL "" FORCE)

set(OPENEXR_FORCE_INTERNAL_DEFLATE 	OFF CACHE BOOL "" FORCE)
set(OPENEXR_FORCE_INTERNAL_IMATH 	ON CACHE BOOL "" FORCE)

set(OPENEXR_INSTALL 			OFF CACHE BOOL "" FORCE)
set(OPENEXR_INSTALL_DOCS 		OFF CACHE BOOL "" FORCE)
set(OPENEXR_INSTALL_PKG_CONFIG 	OFF CACHE BOOL "" FORCE)
set(OPENEXR_INSTALL_TOOLS 		OFF CACHE BOOL "" FORCE)

set(OPENEXR_TEST_LIBRARIES OFF CACHE BOOL "" FORCE)
set(OPENEXR_TEST_PYTHON OFF CACHE BOOL "" FORCE)
set(OPENEXR_TEST_TOOLS OFF CACHE BOOL "" FORCE)
set(OPENEXR_TEST_TOOLS OFF CACHE BOOL "" FORCE)

set(OPENEXR_USE_CLANG_TIDY 			OFF CACHE BOOL "" FORCE)
set(OPENEXR_USE_DEFAULT_VISIBILITY 	OFF CACHE BOOL "" FORCE)